export let stateList = [
  { appr: "AK", name: "Alaska", id: 1 },
  { appr: "AL", name: "Alabama", id: 2 },
  { appr: "AR", name: "Arkansas", id: 3 },
  { appr: "AS", name: "American Samoa", id: 4 },
  { appr: "AZ", name: "Arizona", id: 5 },
  { appr: "CA", name: "California", id: 6 },
  { appr: "CO", name: "Colorado", id: 7 },
  { appr: "CT", name: "Connecticut", id: 8 },
  { appr: "DC", name: "District of Columbia", id: 9 },
  { appr: "DE", name: "Delaware", id: 10 },
  { appr: "FL", name: "Florida", id: 11 },
  { appr: "GA", name: "Georgia", id: 12 },
  { appr: "GU", name: "Guam", id: 13 },
  { appr: "HI", name: "Hawaii", id: 14 },
  { appr: "IA", name: "Iowa", id: 15 },
  { appr: "ID", name: "Idaho", id: 16 },
  { appr: "IL", name: "Illinois", id: 17 },
  { appr: "IN", name: "Indiana", id: 18 },
  { appr: "KS", name: "Kansas", id: 19 },
  { appr: "KY", name: "Kentucky", id: 20 },
  { appr: "LA", name: "Louisiana", id: 21 },
  { appr: "MA", name: "Massachusetts", id: 22 },
  { appr: "MD", name: "Maryland", id: 23 },
  { appr: "ME", name: "Maine", id: 24 },
  { appr: "MI", name: "Michigan", id: 25 },
  { appr: "MN", name: "Minnesota", id: 26 },
  { appr: "MO", name: "Missouri", id: 27 },
  { appr: "MS", name: "Mississippi", id: 28 },
  { appr: "MT", name: "Montana", id: 29 },
  { appr: "NC", name: "North Carolina", id: 30 },
  { appr: "ND", name: "North Dakota", id: 31 },
  { appr: "NE", name: "Nebraska", id: 32 },
  { appr: "NH", name: "New Hampshire", id: 33 },
  { appr: "NJ", name: "New Jersey", id: 34 },
  { appr: "NM", name: "New Mexico", id: 35 },
  { appr: "NV", name: "Nevada", id: 36 },
  { appr: "NY", name: "New York", id: 37 },
  { appr: "OH", name: "Ohio", id: 38 },
  { appr: "OK", name: "Oklahoma", id: 39 },
  { appr: "OR", name: "Oregon", id: 40 },
  { appr: "PA", name: "Pennsylvania", id: 41 },
  { appr: "PR", name: "Puerto Rico", id: 42 },
  { appr: "RI", name: "Rhode Island", id: 43 },
  { appr: "SC", name: "South Carolina", id: 44 },
  { appr: "SD", name: "South Dakota", id: 45 },
  { appr: "TN", name: "Tennessee", id: 46 },
  { appr: "TX", name: "Texas", id: 47 },
  { appr: "UT", name: "Utah", id: 48 },
  { appr: "VA", name: "Virginia", id: 49 },
  { appr: "VI", name: "Virgin Islands", id: 50 },
  { appr: "VT", name: "Vermont", id: 51 },
  { appr: "WA", name: "Washington", id: 52 },
  { appr: "WI", name: "Wisconsin", id: 53 },
  { appr: "WV", name: "West Virginia", id: 54 },
  { appr: "WY", name: "Wyoming", id: 55 }
]

export let serviceLevels = [
  { name: 'Standard', time: 576, desc: 'This is the Standard Service Level Description' },
  { name: 'Express', time: 288, desc: 'This is the Express Service Level Description' }
]

export let orderStatus = [
  { id: 1, status: 'New', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 2, status: 'Name Check', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 3, status: 'Doc Prep', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 4, status: 'State Prep', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 5, status: 'At State', customer_status: 'At State', desc: 'The prepared filing or request has been submitted to the appropriate state or government agency.' },
  { id: 6, status: 'Fulfillment', customer_status: 'Back From State', desc: 'The filing or documents requested are back from the state or government agent and are being reviewed for accuracy.' },
  { id: 7, status: 'Review', customer_status: 'Back From State', desc: 'The filing or documents requested are back from the state or government agent and are being reviewed for accuracy.' },
  { id: 8, status: 'Shipping', customer_status: 'Shipping', desc: 'Congratulations this order has been completed after being reviewed, verified and approved. An electronic copy has been sent and a hard copy when applicable.' },
  { id: 9, status: 'Completed', customer_status: 'Completed', desc: 'This order is completed.' },
  { id: 10, status: 'Cancelled', customer_status: 'Cancelled', desc: '' },
  { id: 11, status: 'Exception', customer_status: 'Exception', desc: 'A required detail appears to be missing from this order. A customer success team member will contact you shortly.' },
  { id: 11, status: 'Hold', customer_status: 'Hold', desc: 'This order has been placed on hold at your request.' },
  { id: 13, status: 'OG Copy', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 19, status: 'IRS', customer_status: 'In Process', desc: 'This order is currently being processed by our team of specialists.' },
  { id: 20, status: 'Pre Order', customer_status: 'Pre Order', desc: 'A pre-order has been created for a required compliance filing. This filing will be completed before the date due with the state.' },
  { id: 31, status: 'Unpaid', customer_status: 'In Process', desc: 'This is an unpaid order created against a company for auto renew.' },
  { id: 39, status: 'Online Filing', customer_status: 'Ready for Online Filing', desc: 'Ready for Online Filing.' },
  { id: 48, status: 'Customer Contact', customer_status: 'Exception', desc: 'Customer Contact.' },
  { id: 49, status: 'Rejection', customer_status: 'Rejection', desc: 'Rejection.' },
  { id: 54, status: 'Bulk Orders', customer_status: 'In Process', desc: 'Bulk Orders.' },
  { id: 70, status: '8821 Follow Up', customer_status: 'In Process', desc: 'Used in EIN Obtainment Process.' },
  { id: 71, status: 'Correction', customer_status: 'Correction', desc: 'This order needs to be corrected and resubmitted.' },
]

export let documentTypes = [
  { id: 1, type: 'Source Order Documents' },
  { id: 2, type: 'Filed Articles' },
  { id: 3, type: 'Final Packet' },
  { id: 4, type: 'EIN/Tax Id' },
  { id: 5, type: 'Supporting Documents' },
  { id: 6, type: 'S-Corp' },
  { id: 7, type: 'Resignation Letter' },
  { id: 8, type: 'Filing Confirmation' },
  { id: 9, type: 'Certificate of Good Standing' },
  { id: 10, type: 'Filed Annual Report' },
  { id: 11, type: 'Certified Documents' },
  { id: 12, type: 'Cover Letter' },
  { id: 13, type: 'SS4' },
  { id: 14, type: 'Other' },
  { id: 15, type: 'IRS Fax Document' },
  { id: 16, type: 'Auto Prepped Document' },
  { id: 17, type: 'SOP' },
  { id: 18, type: 'State Notifications' },
  { id: 19, type: 'Shareholder Action' },
  { id: 20, type: 'Operating Agreement' },
  { id: 21, type: 'Minutes' },
  { id: 22, type: 'Bylaws' },
  { id: 23, type: 'Banking Resolution' },
  { id: 24, type: 'Ein Failure' },
  { id: 25, type: 'Filing Failure' },
  { id: 26, type: 'Annual Meeting Minutes' },
  { id: 27, type: 'BOC-3' },
  { id: 28, type: 'Annual Report - Notice of Due Date' },
  { id: 29, type: 'Business License' },
  { id: 30, type: 'CCF/CCF Info' },
  { id: 31, type: 'Mail Forwarding' },
  { id: 32, type: 'Signed Consent/Action' },
  { id: 33, type: 'Corporate Registration Notification' },
  { id: 34, type: 'DOT' },
  { id: 35, type: 'IRS Notices' },
  { id: 36, type: 'Change of Registered Agent Address' },
  { id: 37, type: 'BOC-3' },
  { id: 38, type: 'Annual Report - Notice of Due Date' },
  { id: 39, type: 'Dissolution Notice' },
  { id: 40, type: '8821 Form' },
  { id: 41, type: 'Customer Invoice' },
  { id: 42, type: 'Invoice Report' },
  { id: 43, type: 'Other' },
  { id: 44, type: 'Filed Publication' },
];

export let companyState = [
  { id: 23, status: 'Not Available', customer_status: 'Not Available', desc: "This entity's status with the Secretary of State is Not Available." },
  { id: 24, status: 'Delinquent', customer_status: 'Delinquent', desc: "This entity has failed to maintain good standing with the Secretary of State." },
  { id: 25, status: 'Administratively Dissolved', customer_status: 'Administratively Dissolved', desc: "The state has administratively dissolved this entity, revoking its right to maintain its registration with the state as a legal entity." },
  { id: 26, status: 'Dissolved', customer_status: 'Dissolved', desc: "This entity is no longer registered as an active business with the Secretary of State." },
  { id: 27, status: 'Revoked', customer_status: 'Revoked', desc: "This entity has failed to maintain good standing with the Secretary of State." },
  { id: 28, status: 'Default', customer_status: 'Default', desc: "This entity has failed to maintain good standing with the Secretary of State." },
  { id: 29, status: 'Good Standing', customer_status: 'Good Standing', desc: "This entity is registered and active with the Secretary of State." },
  { id: 30, status: 'Not in Good Standing', customer_status: 'Not in Good Standing', desc: "This entity has failed to maintain good standing with the Secretary of State." },
  { id: 56, status: 'Inactive: Unknown', customer_status: 'Inactive: Unknown', desc: "The entiy is inactive at the SOS" },
  { id: 57, status: 'Inactive: Voluntary', customer_status: 'Inactive: Voluntary', desc: "The entity is inactive at the SOS due to a voluntary action bt the entity (I.e. merger, dissolution, conversion)" },
  { id: 58, status: 'Inactive: Involuntary', customer_status: 'Inactive: Involuntary', desc: "The entity is inactive at the SOS due to an involuntary action by the entity (I.e. administratively dissolved)" },
  { id: 59, status: 'Active', customer_status: 'Active', desc: "The entity is active at the SOS" },
  { id: 60, status: 'Active In Danger', customer_status: 'Active In Danger', desc: "The entity is active at the SOS but may be late on an annual reprot or tax payment" },
  { id: 62, status: 'Pending', customer_status: 'Pending', desc: "The entity at the SOS is pending approval " },
]

export let company = [
  { id: 21, status: 'Pending' },
  { id: 22, status: 'Active' },
  { id: 55, status: 'Inactive' },
]

export let user = [
  { id: 43, status: 'Active' },
  { id: 44, status: 'Pending' },
  { id: 45, status: 'Inactive' },
]

export let sopDocuments = [
  { id: 50, status: 'New Doc' },
  { id: 51, status: 'Acnknowledged' },
  { id: 52, status: 'Viewed' },
  { id: 53, status: 'Legacy' },
]

export let entities = [
  { name: 'LLC' },
  { name: 'Corporation' },
  { name: 'Non-profit' },
  { name: 'Limited Partnership' },
  { name: 'Limited Liability Partnership' },
  { name: 'Other' },
  { name: 'Not Assigned' },
  { name: 'S-Corp' },
  { name: 'Sole-Proprietorship' },
  { name: 'DBA' },
  { name: 'General Partnership' }
]

export let productSelection = [
  { name: 'Preparation of Articles', price: '$60.00' },
  { name: 'Registered Agent Subscription', price: '$199.00 / year' },
  { name: 'Automated Report Filings Subscription', price: '$129.00 / year' },
  { name: 'Membership Certificates', price: '$49.00' },
  { name: 'Employer Identification Number / TAX ID', price: '$59.00' },
  { name: 'LLC Kit & Seal Package', price: '$79.00' },
  { name: 'S-Corp Election', price: '$39.00' },
  { name: 'Certificate of Good Standing', price: '$45.00' },
  { name: 'Business License Report', price: '$119.00' },
  { name: 'Operating Agreement', price: '$39.00' },
]

export let businessPurpose = [
  { id: 7, name: 'Accommodation & Food Service' },
  { id: 25, name: 'Any Legal Purpose' },
  { id: 14, name: 'Church' },
  { id: 23, name: 'Clubs and Organizations' },
  { id: 16, name: 'Educational Purpose' },
  { id: 24, name: 'Encourage amateur sports competition' },
  { id: 5, name: 'Finance & Insurance' },
  { id: 12, name: 'General Charitable Purpose' },
  { id: 6, name: 'Health care and Social Assistance' },
  { id: 17, name: 'Literary Purpose' },
  { id: 3, name: 'Manufacturing' },
  { id: 15, name: 'Other Religious Purpose' },
  { id: 22, name: 'Public Safety Purposes' },
  { id: 1, name: 'Real Estate' },
  { id: 2, name: 'Rental & Leasing' },
  { id: 10, name: 'Retail' },
  { id: 18, name: 'Scientific Purpose' },
  { id: 13, name: 'To create a charitable risk pool' },
  { id: 20, name: 'To provide Child-care outside home' },
  { id: 19, name: 'To provide Hospital or Medical Care' },
  { id: 21, name: 'To provide housing for low-income, the elderly or the handicapped' },
  { id: 4, name: 'Transportation & Warehousing' },
  { id: 8, name: 'Wholesale- AgentBroker' },
  { id: 9, name: 'Wholesale- Other' },
  { id: 11, name: 'Other' },
]

export let businessActivity = [
  { name: 'Accommodations', id: 1 },
  { name: 'Construction', id: 2 },
  { name: 'Consulting', id: 3 },
  { name: 'Entertainment', id: 4 },
  { name: 'Finance', id: 5 },
  { name: 'Food Service', id: 6 },
  { name: 'Healthcare', id: 7 },
  { name: 'Insurance', id: 8 },
  { name: 'Manufacturing', id: 9 },
  { name: 'Profressional', id: 10 },
  { name: 'Real Estate', id: 11 },
  { name: 'Registered Agent Services', id: 12 },
  { name: 'Retail', id: 13 },
  { name: 'Social Assistance', id: 14 },
  { name: 'Technology', id: 15 },
  { name: 'Transporation', id: 16 },
  { name: 'Warehousing', id: 17 },
  { name: 'Wholesale', id: 18 },
  { name: 'Other', id: 19 },
]